version: 2

sources:
    - name: staging
      database: taxi-rides-ny-339813  # For bigquery -project
      schema: trips_data_all          # -dataset

      tables:
        - name: green_tripdata
        - name: yellow_tripdata
          freshness:
            error_after: {count: 6, period: hour}